dist: trusty
sudo: false
language: python
python:
    - "3.6"
install:
    - sudo apt-get install -y graphviz
    - pip install tox-travis pytest
script:
    - tox
deploy:
  provider: pypi
  skip_cleanup: true
  user: Secbone
  password:
    secure: M06CzKawqt24Om0gSGveGrg5Kke9+HWORJ3jgaIs2fBpD+7hjo3RRkMGRaDKyzu7yIW5/K+57799CzBF42ga7o3WykdbYAnQeW55c0O6s88tuFpar+sNPoB/2eSQQB76j/tHKs8qjlCUKzl2X8zy/hu/EYYjo0PDmp8xDokLWpU/od58bebBEL/iedzgXZrmD5C0WKtg4tUSZtBDb4nCno55SnNq1eiIw5ANT2kb8yad3arx7oj97V6/YG1FYyAgjlv7YOr2er7nmKojfHPMdIDDvrlazeBfXaOZfvOfGLtFnvprJNLwECnedynDpRrnvOc8X0fAZUoayuo2SyVo/pxVW1JNmvk0GKMoa0mX8UEMSA79w4/qt9KZBWacPdT9NjhzsDoOUlogxHShojXXlansE5kAXRUfzlFL2R8lbAmbfqsdw6AriVfMtp77/j2j8kwJCZEPoqHSRSdJgqZsiSx7Mb8szI10Yg2FSqHAqMdPrAR7Wl6JZWMlLnGQ9aacHDpE6CpeHb5ibZusAZMfOWF49+KxQWFiLR91k2ji03Hq9L4AD/w9+A4gWRQ/TMNgYdk8yUFli1m33XClHaSgwpUaC1JrxhuKBkeptrRItxO5hMJ4CaEAhDkyCPXdsASXEZ5Nug2lqbzQYaCrqz6xUpPM5OUNyZl7uysjaQIt3Oo=
  on:
    tags: true
    distributions: sdist bdist_wheel --universal
    repo: amphibian-dev/toad
